<a href="https://colab.research.google.com/github/imdebarun/tensorflow2/blob/main/Getting_started_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Getting started with tensor is to understand the funtionality of each attibutes.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [3]:
vector = tf.constant([3,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

In [4]:
matrix = tf.constant([[3,9],[1,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [1, 3]], dtype=int32)>

In [5]:
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [6]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [7]:
tensor.ndim

3

In [8]:
## Creating tensor with tf.Variable:
# create the same tensor with tf.Variable() as before -
Changeable_tensor = tf.Variable([3,9])
Unchangeable_tensor = tf.constant([3,9])
Changeable_tensor, Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>)

In [9]:
# Changeable_tensor[0] = 7
# Changeable_tensor
Changeable_tensor[0].assign(7)
Changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 9], dtype=int32)>

Creating Random Tensor :

In [10]:
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape = (3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
rand2 = tf.random.Generator.from_seed(42)
rand2 = rand2.normal(shape = (3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
rand1==rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Shuffle the order elements of a tensor:-

In [13]:
tensor_a = tf.constant([[10,7],[3,4],[2,3]])
tensor_a, tensor_a.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  3]], dtype=int32)>,
 2)

In [14]:
tf.random.shuffle(tensor_a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  3],
       [10,  7]], dtype=int32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_a, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  3]], dtype=int32)>

Other ways to create a tenosr -

In [16]:
# cretae tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
#create a tensor of all zeros -
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensor:
* the main difference between numpy arrays and TensorFlow tensors is taht tensors can be run on GPU for much faster computing.

In [18]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [20]:
B = tf.constant(numpy_A, shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Tensor Attributes --
* Shape - The length or number of elements of each of the dimensions of a tensor.
* Rank - The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a tensor has rank n.
* Axis or Dimension - A particular dimension of a tensor.
* Size - The total number of items in the tensor.

In [21]:
rank_5_tensor = tf.zeros(shape = [2,3,4,5,6])
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [22]:
rank_5_tensor[0]

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

In [23]:
rank_5_tensor.shape, rank_5_tensor.ndim, tf.size(rank_5_tensor)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [24]:
# Get various attributes of our tensor -
print("Datatype of every Element:", rank_5_tensor.dtype)
print("Number of dimensions (rank):", rank_5_tensor.ndim)
print("Shape of tenosr:", rank_5_tensor.shape)
print("Elements along the 0 axis:", rank_5_tensor.shape[0])
print("Elements along the last axis:", rank_5_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_5_tensor).numpy())

Datatype of every Element: <dtype: 'float32'>
Number of dimensions (rank): 5
Shape of tenosr: (2, 3, 4, 5, 6)
Elements along the 0 axis: 2
Elements along the last axis: 6
Total number of elements in our tensor: 720


### Indexing tensors:
 Tensors can be indexed just like python list

In [25]:
#Get the first 2 elements of each dimension
rank_5_tensor[:2,:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [26]:
# Get the first elemnent from each dimension from except for the final one.
rank_5_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1, 6), dtype=float32, numpy=array([[[[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [27]:
rank_5_tensor[:1,:1,:,:1,:1]

<tf.Tensor: shape=(1, 1, 4, 1, 1), dtype=float32, numpy=
array([[[[[0.]],

         [[0.]],

         [[0.]],

         [[0.]]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[3,9],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [3, 4]], dtype=int32)>

In [29]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 4], dtype=int32)>

In [30]:
# Add in extra dimensoin to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [9]],

       [[3],
        [4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [9]],

       [[3],
        [4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 - axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 9],
        [3, 4]]], dtype=int32)>

# Manipulating tensors (tensor operations) :
**Basic Operations**
`+`,`-`,`*`,`/`

In [33]:
# You can add values to a tensor using addition operator:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [35]:
# Multiplication also works -
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
# subtration :
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
# We can use the tensorflow built-in functions to Multiply too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication** :
* In machine learning, matrix multiplication is one of the most common operations. There are two rules our tensors (or matrices) need to fulfil if we are going to matrix multiply them -
1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimensions

In [38]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [39]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
# matrix multiplication with Python `@` operator :
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
tensor.shape

TensorShape([2, 2])

In [42]:
# Create a tensor of shape (3,2)
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another tensor of shape (3,2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
# Try to matrix multiply tensors of same shape
# X@Y
# tf.matmul(X, Y)

In [46]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [47]:
# Try to multiply X by reashped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [48]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [51]:
# Can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [52]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Matrix Multiplication or The DOT Product**
You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [54]:
tf. tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [55]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [56]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [57]:
# Check the values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n") #"\n" is for new line
print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [58]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Chaning the datatype of a tensor: