<a href="https://colab.research.google.com/github/imdebarun/tensorflow2/blob/main/Getting_started_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Getting started with tensor is to understand the funtionality of each attibutes.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [3]:
vector = tf.constant([3,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

In [4]:
matrix = tf.constant([[3,9],[1,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [1, 3]], dtype=int32)>

In [5]:
scalar.ndim, vector.ndim, matrix.ndim

(0, 1, 2)

In [6]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [7]:
tensor.ndim

3

In [8]:
## Creating tensor with tf.Variable:
# create the same tensor with tf.Variable() as before -
Changeable_tensor = tf.Variable([3,9])
Unchangeable_tensor = tf.constant([3,9])
Changeable_tensor, Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>)

In [9]:
# Changeable_tensor[0] = 7
# Changeable_tensor
Changeable_tensor[0].assign(7)
Changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 9], dtype=int32)>

Creating Random Tensor :

In [10]:
rand1 = tf.random.Generator.from_seed(42)
rand1 = rand1.normal(shape = (3,2))
rand1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
rand2 = tf.random.Generator.from_seed(42)
rand2 = rand2.normal(shape = (3,2))
rand2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [12]:
rand1==rand2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Shuffle the order elements of a tensor:-

In [13]:
tensor_a = tf.constant([[10,7],[3,4],[2,3]])
tensor_a, tensor_a.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  3]], dtype=int32)>,
 2)

In [14]:
tf.random.shuffle(tensor_a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(tensor_a, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  3]], dtype=int32)>

Other ways to create a tenosr -

In [16]:
# cretae tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
#create a tensor of all zeros -
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensor:
* the main difference between numpy arrays and TensorFlow tensors is taht tensors can be run on GPU for much faster computing.

In [18]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [20]:
B = tf.constant(numpy_A, shape = (2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Tensor Attributes --
* Shape - The length or number of elements of each of the dimensions of a tensor.
* Rank - The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a tensor has rank n.
* Axis or Dimension - A particular dimension of a tensor.
* Size - The total number of items in the tensor.

In [21]:
rank_5_tensor = tf.zeros(shape = [2,3,4,5,6])
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [22]:
rank_5_tensor[0]

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

In [23]:
rank_5_tensor.shape, rank_5_tensor.ndim, tf.size(rank_5_tensor)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [24]:
# Get various attributes of our tensor -
print("Datatype of every Element:", rank_5_tensor.dtype)
print("Number of dimensions (rank):", rank_5_tensor.ndim)
print("Shape of tenosr:", rank_5_tensor.shape)
print("Elements along the 0 axis:", rank_5_tensor.shape[0])
print("Elements along the last axis:", rank_5_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_5_tensor).numpy())

Datatype of every Element: <dtype: 'float32'>
Number of dimensions (rank): 5
Shape of tenosr: (2, 3, 4, 5, 6)
Elements along the 0 axis: 2
Elements along the last axis: 6
Total number of elements in our tensor: 720


### Indexing tensors:
 Tensors can be indexed just like python list

In [25]:
#Get the first 2 elements of each dimension
rank_5_tensor[:2,:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [26]:
# Get the first elemnent from each dimension from except for the final one.
rank_5_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1, 6), dtype=float32, numpy=array([[[[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [27]:
rank_5_tensor[:1,:1,:,:1,:1]

<tf.Tensor: shape=(1, 1, 4, 1, 1), dtype=float32, numpy=
array([[[[[0.]],

         [[0.]],

         [[0.]],

         [[0.]]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[3,9],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 9],
       [3, 4]], dtype=int32)>

In [29]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 4], dtype=int32)>

In [30]:
# Add in extra dimensoin to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [9]],

       [[3],
        [4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [9]],

       [[3],
        [4]]], dtype=int32)>

In [32]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 - axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 9],
        [3, 4]]], dtype=int32)>

# Manipulating tensors (tensor operations) :
**Basic Operations**
`+`,`-`,`*`,`/`

In [33]:
# You can add values to a tensor using addition operator:
tensor = tf.constant([[10,7],
                      [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [34]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [35]:
# Multiplication also works -
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
# subtration :
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
# We can use the tensorflow built-in functions to Multiply too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication** :
* In machine learning, matrix multiplication is one of the most common operations. There are two rules our tensors (or matrices) need to fulfil if we are going to matrix multiply them -
1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimensions

In [38]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [39]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
# matrix multiplication with Python `@` operator :
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [41]:
tensor.shape

TensorShape([2, 2])

In [42]:
# Create a tensor of shape (3,2)
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another tensor of shape (3,2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [43]:
# Try to matrix multiply tensors of same shape
# X@Y
# tf.matmul(X, Y)

In [44]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [45]:
# Try to multiply X by reashped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [46]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [47]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [48]:
# Can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [49]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Matrix Multiplication or The DOT Product**
You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()

In [50]:
tf. tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [51]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [52]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [53]:
# Check the values of Y, reshaped Y and transposed Y
print("Normal Y:")
print(Y, "\n") #"\n" is for new line
print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [54]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose(rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Chaning the datatype of a tensor:

In [55]:
# Create a new tensor with default datatype (float 32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [56]:
C = tf.constant([3,4])
C.dtype

tf.int32

In [57]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [58]:
# Change from int32 to flaot 32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [59]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 4.], dtype=float16)>

### Aggregating Tensors:
Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [60]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
# GEt the absolute values:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Let's got through the following forms of aggregation :
* Get the maximum
* Get the minimum
* Get the mean of the tensor
* Get the sum of the tensor
* Get the Variance
* Get the Standard deviation

In [62]:
# Create a random tensor with values between 0 and 100 of size 50
F = tf.constant(np.random.randint(0,100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 80, 24, 95, 38, 30, 28, 19, 30, 97, 92, 89, 12, 20, 85, 63,  6,
       33, 66, 22, 83, 77, 48, 22, 43, 82,  8, 31, 80, 45,  5, 42,  9, 58,
        3, 36, 37, 88, 10,  3, 16, 89, 85, 97, 42, 28, 65, 49, 65, 37])>

In [63]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [64]:
# Find the minimum
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [65]:
# Get the maximum
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [66]:
# Find the mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [67]:
# Find the sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2364>

In [68]:
# GEt the variance
tf.math.reduce_variance(tf.cast(F, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=875.80164>

In [69]:
# GEt the standard deviation
tf.math.reduce_std(tf.cast(F, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.593946>

In [70]:
# To find the variance of our tensor, we need access to tensorflow probabability
import tensorflow_probability as tfp

In [71]:
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=875>

### **Find the positional Maximum and Minimum of a tensor**


In [72]:
# Create a new tensor for finding positional maximum or minimum
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [73]:
# Find the positional maximum
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [74]:
# Index on our largest value position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [75]:
# Find the maximum value of G
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
# Check the equality
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
# Find the positional minimum
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [79]:
# Find the minimum using the positional minimum index
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [81]:
### Squeezing a tensor (removing all single dimensions)
tf.random.set_seed(42)
H = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [82]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [83]:
H_squeezed = tf.squeeze(H)
H_squeezed, H_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One hot encoding tensors

In [84]:
# Create a list of inices
some_list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
# sPecify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deeplearning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deeplearning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deeplearning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deeplearning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deeplearning']], dtype=object)>

### Squaring, log, square_root math operations

In [86]:
# create a new tensor
J = tf.range(1,10)
J

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [88]:
# Square it -
tf.square(J)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [91]:
# Square root -

tf.math.sqrt(tf.cast(J, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [92]:
# Find the log
tf.math.log(tf.cast(J, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
- Tensorflow interacts beautifully with Numpy array

In [93]:
# Create a tensor directly from a Numpy array -
K = tf.constant(np.array([3.,7.,10.]))
K

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [94]:
np.array(K), type(np.array(K))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [95]:
# Convert tensor K to a Numpy array
K.numpy(), type(K.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [97]:
# The default types of each are slightly different
numpy_K = tf.constant(np.array([3.,7.,10.]))
tensor_K = tf.constant([3.,7.,10.])
# Check the data type of each
numpy_K.dtype, tensor_K.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [99]:
tf.config.list_logical_devices("GPU")

[]